name: Build and Package VSIX

on:
  push:
    tags:
      - 'v*'  # 例えば v0.1.0 のように "v" で始まるタグをトリガーにする

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 必要に応じて変更

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run compile
        # 拡張機能のビルドコマンドがあれば (例: `npm run build`) そちらを使用

      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension
        run: vsce package
        # 成功すると "<extension-name>-<version>.vsix" ファイルが生成される

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-artifact
          path: '*.vsix'

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automatic release of VSIX"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_GitHub_Release.outputs.upload_url }}
          asset_path: "*.vsix"
          asset_name: "extension.vsix"
          asset_content_type: "application/octet-stream"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}