name: Build and Package VSIX

on:
  push:
    tags:
      - 'v*'  # 例えば v0.1.0 のように "v" で始まるタグをトリガーにする

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run compile

      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension
        run: vsce package
        # 成功すると "<extension-name>-<version>.vsix" ファイルが生成される

      - name: Release
        run: |
          gh release create ${{github.ref_name}} --generate-notes *.vsix
        env:
          GH_TOKEN: ${{ github.token }}
